document.writeln("  <script src=\'https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.min.js\'></script>");
document.writeln("  <script src=\'https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.2.2/js/bootstrap.bundle.min.js\'></script>");
document.writeln("  <script src=\'https://cdn.bootcdn.net/ajax/libs/glightbox/3.2.0/js/glightbox.min.js\'></script>");
document.writeln("  <script src=\'https://cdn.bootcdn.net/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js\'></script>");
document.writeln("  <script src=\'https://cdn.bootcdn.net/ajax/libs/validate-js/2.0.1/validate.js\'></script>");
document.writeln("  <script src=\'https://cdn.jsdelivr.net/npm/@srexi/purecounterjs@1.5.0/js/purecounter.js\'></script>");
document.writeln("  <script src=\'https://cdn.bootcdn.net/ajax/libs/Swiper/8.4.4/swiper-bundle.min.js\'></script>");
//document.writeln("  <script src=\'../../../../../../live2d_models/lib/L2Dwidget.min.js?094cbace49a39548bed64abff5988b05\'></script>");
//document.writeln("  <script>L2Dwidget.init({\'pluginRootPath\':\'../../../../../../live2d_models/\',\'pluginJsPath\':\'../../../../../../live2d_models/lib/\',\'pluginModelPath\':\'../../../../../../assets/\',\'tagMode\':false,\'log\':false,\'model\':{\'jsonPath\':\'../../../../../../live2d_models/assets/assets/shizuku.model.json\'},\'display\':{\'position\':\'left\',\'width\':150,\'height\':300},\'mobile\':{\'show\':true}});");
//document.writeln("  </script>");
document.writeln("  <script src=\'../../../../../../assets/js/main.js\'></script> ");
document.writeln("  <script type=\'text/javascript\' color=\'79,172,254\' opacity=\'0.7\' zIndex=\'-1\' count=\'200\' src=\'//cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js\'></script>");